# Generated by Django 4.1.7 on 2023-03-24 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
                ("video_preview", models.FileField(upload_to="courses/previews/")),
                ("studies_plan", models.FileField(upload_to="courses/studies_plans/")),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "course_type",
                    models.CharField(
                        choices=[
                            ("O", "Online - Recorded"),
                            ("L", "Online - Live"),
                            ("D", "On-Demand"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "course_age",
                    models.CharField(
                        choices=[
                            ("A", "All"),
                            ("5", "5 - 7"),
                            ("8", "8 - 9"),
                            ("10", "10 - 11"),
                            ("12", "12 - 15"),
                            ("16", "16 - 18"),
                        ],
                        max_length=2,
                    ),
                ),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CourseInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("capacity", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="miniedu.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EduProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("image", models.ImageField(blank=True, upload_to="profile-images/")),
                (
                    "profile_type",
                    models.CharField(
                        choices=[("P", "Parent"), ("S", "Student"), ("T", "Teacher")],
                        default="S",
                        max_length=1,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="miniedu.eduprofile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_enrolled", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="miniedu.courseinstance",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="miniedu.eduprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("1", "Monday"),
                            ("2", "Tuesday"),
                            ("3", "Wednesday"),
                            ("4", "Thursday"),
                            ("5", "Friday"),
                            ("6", "Saturday"),
                            ("7", "Sunday"),
                        ],
                        max_length=1,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="miniedu.courseinstance",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="courseinstance",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="miniedu.eduprofile"
            ),
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
                ("deliverable", models.FileField(upload_to="deliverables/")),
                ("due_date", models.DateField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="miniedu.course"
                    ),
                ),
            ],
        ),
    ]
